name: Deploy
on: 
    pull_request:
        types:
            - closed

jobs:
  run_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.yarn/cache
            src/packages/*/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('src/**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: |
            cd src
            yarn install

      - name: Fix and Check Lint
        run: |
            cd src
            yarn workspace business lint

  run_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.yarn/cache
            src/packages/*/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('src/**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: |
          cd src
          yarn install

      - name: Build project
        run: |
          cd src
          yarn workspace client-ui build